
version: '3'

services:
  obtain-opensbi:
    image: alpine/git
    volumes:
      - ./:/work
    working_dir: /work/
    command: |
      clone -c advice.detachedHead=false -b v1.3.1 --depth 1 --single-branch https://github.com/riscv-software-src/opensbi

  build-opensbi:
    depends_on:
       - obtain-opensbi
    build:
      context: .
      dockerfile: Dockerfile-opensbi
    platform: linux/riscv64
    volumes:
      - ./opensbi:/work
    working_dir: /work/
    # Can't figure out how to pass `nproc` to make, so using 10, change or fix.
    command: make PLATFORM=generic FW_JUMP=y FW_JUMP_ADDR=0x80200000 FW_JUMP_FDT_ADDR=0x87e00000 -j 10

  obtain-linux:
    image: alpine/git
    volumes:
      - ./:/work
    working_dir: /work/
    command: |
      clone -c advice.detachedHead=false -b v6.6.33 --depth 1 --single-branch https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

  config-linux:
    depends_on:
      - obtain-linux
    image: alpine
    volumes:
      - ./:/work
    working_dir: /work/linux
    # Copy the custom kernel configuration to the appropriate place
    command: |
      cp /work/config_with_gpu_numa.config .config

  build-linux:
    depends_on:
      - obtain-linux
      - config-linux
    build:
      context: .
      dockerfile: Dockerfile-linux
    volumes:
      - ./linux:/work
    working_dir: /work/
    platform: linux/riscv64
    # Couldn't get -j`nproc` to work, so using 10, change or fix.
    command: make -j 10