FROM ubuntu:24.04

# Install necessary packages (QEMU, VNC, Xfce, etc.)
RUN apt-get update && apt-get install -y \

    u-boot-qemu \
    qemu-system-misc \
    opensbi \
    qemu-utils \
    git \
    wget \
    unzip \
    pipewire \
    pipewire-audio-client-libraries
